enum ward25NamesNumbers {
  "",
  "Etobicoke North",
  "Etobicoke Centre",
  "Etobicoke Lakeshore",
  "Parkdale High Park",
  "York South Weston",
  "York Centre",
  "Humber River Black Creek",
  "Eglinton Lawrence",
  "Davenport",
  "Spadina Fort York",
  "University Rosedale",
  "Toronto St. Pauls",
  "Toronto Centre",
  "Toronto Danforth",
  "Don Valley West",
  "Don Valley East",
  "Don Valley North",
  "Willowdale",
  "Beaches East York",
  "Scarborough Southwest",
  "Scarborough Centre",
  "Scarborough Agincourt",
  "Scarborough North",
  "Scarborough Guildwood",
  "Scarborough Rouge Park",
}

export default ward25NamesNumbers;
