export const ward25NamesNumbers: Record<number, string> = {
  1: "etobicoke_north",
  2: "etobicoke_centre",
  3: "etobicoke_lakeshore",
  4: "parkdale_high_park",
  5: "york_south_weston",
  6: "york_centre",
  7: "humber_river_black_creek",
  8: "eglinton_lawrence",
  9: "davenport",
  10: "spadina_fort_york",
  11: "university_rosedale",
  12: "toronto_st_pauls",
  13: "toronto_centre",
  14: "toronto_danforth",
  15: "don_valley_west",
  16: "don_valley_east",
  17: "don_valley_north",
  18: "willowdale",
  19: "beaches_east_york",
  20: "scarborough_southwest",
  21: "scarborough_centre",
  22: "scarborough_agincourt",
  23: "scarborough_north",
  24: "scarborough_guildwood",
  25: "scarborough_rouge_park",
};
