import { FieldPath, WhereFilterOp } from "firebase/firestore";

export type FilterType =
  | "AIR_CONDITIONING_TYPE"
  | "BARRIER_FREE_ACCESSIBILTY_ENTR"
  | "BALCONIES"
  | "BIKE_PARKING"
  | "NO_OF_ELEVATORS"
  | "DESCRIPTION_OF_INDOOR_EXERCISE_ROOM"
  | "HIGH_RISE"
  | "LAUNDRY_ROOM"
  | "LOCKER_OR_STORAGE_ROOM"
  | "LOW_RISE"
  | "MID_RISE"
  | "NON_SMOKING_BUILDING"
  | "PARKING_TYPE"
  | "PETS_ALLOWED"
  | "YEAR_BUILT";

export type Sort = "ward_number" | "year_built_asc" | "year_built_desc";

export type FirestoreWhereClause = {
  fieldPath: string | FieldPath;
  opStr: WhereFilterOp;
  value: unknown;
};

export type FilterOption = {
  key: FilterType;
  label: string;
  iconClass: string;
};

export type AppliedFilterMap = {
  [key in FilterType]?: FirestoreWhereClause[];
};

export type AppSearchParams = {
  sort?: Sort;
  q?: string;
  year_built_start?: number;
  year_built_end?: number;
  features?: string[];
};

export type FetchDataResponse = {
  objectID?: string; // Generated by Algolia when adding records to an index
  _id: number;
  AIR_CONDITIONING_TYPE: string;
  BALCONIES: boolean;
  BARRIER_FREE_ACCESSIBILTY_ENTR: boolean;
  BIKE_PARKING: boolean;
  CONFIRMED_STOREYS: number;
  CONFIRMED_UNITS: number;
  DESCRIPTION_OF_INDOOR_EXERCISE_ROOM: string;
  DESCRIPTION_OF_OUTDOOR_REC_FACILITIES: string;
  FACILITIES_AVAILABLE: string;
  FIRE_ALARM: boolean;
  HEATING_TYPE: string;
  LAUNDRY_ROOM: boolean;
  LOCKER_OR_STORAGE_ROOM: boolean;
  NO_BARRIER_FREE_ACCESSBLE_UNITS: number;
  NO_OF_ACCESSIBLE_PARKING_SPACES: number;
  NO_OF_ELEVATORS: number;
  NO_OF_LAUNDRY_ROOM_MACHINES: number;
  NON_SMOKING_BUILDING: boolean;
  PARKING_TYPE: string[];
  PCODE: string;
  PET_RESTRICTIONS: string;
  PETS_ALLOWED: boolean;
  PROP_MANAGEMENT_COMPANY_NAME: string;
  PROPERTY_TYPE: string;
  SEPARATE_GAS_METERS_EACH_UNIT: boolean;
  SEPARATE_HYDRO_METER_EACH_UNIT: boolean;
  SEPARATE_WATER_METERS_EA_UNIT: boolean;
  SITE_ADDRESS: string;
  VISITOR_PARKING: string;
  WARD: number;
  YEAR_BUILT: number;
};
